FROM golang:1.24.3 AS builder

WORKDIR /app
COPY backend/go.mod backend/go.sum ./
RUN go mod download

COPY backend ./backend
RUN cd backend && go build -o /app/server .

FROM golang:1.24.3
WORKDIR /app
COPY --from=builder /app/server .
EXPOSE 3000
CMD ["./server"]